# Explore Classify Fine Tuned Modles Results
Notebook for exporing the classify results for the fine tuned models.
The result are stored in `../output/evaluation_results/ classify_finetuned_*.csv`.  
The classify DSPy results contain standard ML metrics such as accuracy, precission, etc.

In [1]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

----

## Load all classifaction results

In [2]:
classify_files = glob.glob('../output/evaluation_results/classify_finetuned_*.csv')
len(classify_files)

5

In [3]:
classify_df = pd.concat([pd.read_csv(file) for file in classify_files])
classify_df.head()

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
0,finetuned-qwen7b,overall,all,all,0.81,0.73,0.67,0.66,110,82,21,133,28
1,finetuned-qwen7b,macro_avg,rigidity,all,0.83,0.71,0.73,0.59,22,16,5,39,6
2,finetuned-qwen7b,per_class,rigidity,+R,0.82,0.87,0.87,0.87,15,13,2,5,2
3,finetuned-qwen7b,per_class,rigidity,-R,0.86,0.25,1.00,0.40,1,1,3,18,0
4,finetuned-qwen7b,per_class,rigidity,~R,0.82,1.00,0.33,0.50,6,2,0,16,4

----

## Explore overall scores

looking at just f1_score, the non-agent large llms w/o dspy do best.

In [4]:
overall_df = classify_df.query("property == 'all'").sort_values(by='f1_score', ascending=False)
overall_df.head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
0,finetuned-qwen7b,overall,all,all,0.81,0.73,0.67,0.66,110,82,21,133,28
0,finetuned-gemma9b,overall,all,all,0.67,0.47,0.45,0.43,110,58,34,120,52
0,finetuned-llama8b,overall,all,all,0.75,0.31,0.43,0.36,110,77,33,121,33
0,finetuned-llama3b,overall,all,all,0.58,0.36,0.39,0.33,110,54,56,98,56
0,finetuned-mistral7b,overall,all,all,0.60,0.40,0.36,0.32,110,52,48,106,58

---

## Expore rigidity

In [5]:
rigidity_df = classify_df.query("property == 'rigidity'").sort_values(by='f1_score', ascending=False)
rigidity_df[rigidity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
1,finetuned-qwen7b,macro_avg,rigidity,all,0.83,0.71,0.73,0.59,22,16,5,39,6
1,finetuned-gemma9b,macro_avg,rigidity,all,0.65,0.29,0.29,0.29,22,10,11,33,12
1,finetuned-llama3b,macro_avg,rigidity,all,0.79,0.23,0.33,0.27,22,15,7,37,7
1,finetuned-llama8b,macro_avg,rigidity,all,0.79,0.23,0.33,0.27,22,15,7,37,7
1,finetuned-mistral7b,macro_avg,rigidity,all,0.48,0.19,0.09,0.12,22,4,16,28,18

In [6]:
rigidity_df[rigidity_df['class'] == '+R'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
2,finetuned-qwen7b,per_class,rigidity,+R,0.82,0.87,0.87,0.87,15,13,2,5,2
2,finetuned-llama3b,per_class,rigidity,+R,0.68,0.68,1.00,0.81,15,15,7,0,0
2,finetuned-llama8b,per_class,rigidity,+R,0.68,0.68,1.00,0.81,15,15,7,0,0
2,finetuned-gemma9b,per_class,rigidity,+R,0.45,0.62,0.53,0.57,15,8,5,2,7
2,finetuned-mistral7b,per_class,rigidity,+R,0.36,0.57,0.27,0.36,15,4,3,4,11

In [7]:
rigidity_df[rigidity_df['class'] == '-R'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
3,finetuned-qwen7b,per_class,rigidity,-R,0.86,0.25,1.0,0.4,1,1,3,18,0
3,finetuned-mistral7b,per_class,rigidity,-R,0.36,0.00,0.0,0.0,1,0,13,8,1
3,finetuned-gemma9b,per_class,rigidity,-R,0.95,0.00,0.0,0.0,1,0,0,21,1
3,finetuned-llama8b,per_class,rigidity,-R,0.95,0.00,0.0,0.0,1,0,0,21,1
3,finetuned-llama3b,per_class,rigidity,-R,0.95,0.00,0.0,0.0,1,0,0,21,1

In [8]:
rigidity_df[rigidity_df['class'] == '~R'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
4,finetuned-qwen7b,per_class,rigidity,~R,0.82,1.00,0.33,0.50,6,2,0,16,4
4,finetuned-gemma9b,per_class,rigidity,~R,0.55,0.25,0.33,0.29,6,2,6,10,4
4,finetuned-llama8b,per_class,rigidity,~R,0.73,0.00,0.00,0.00,6,0,0,16,6
4,finetuned-llama3b,per_class,rigidity,~R,0.73,0.00,0.00,0.00,6,0,0,16,6
4,finetuned-mistral7b,per_class,rigidity,~R,0.73,0.00,0.00,0.00,6,0,0,16,6

In [9]:
rigidity_df['class'].unique()

array(['+R', 'all', '~R', '-R'], dtype=object)

---

## Explore Identity

In [10]:
identity_df = classify_df.query("property == 'identity'").sort_values(by='f1_score', ascending=False)
identity_df[identity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
5,finetuned-qwen7b,macro_avg,identity,all,0.95,1.00,0.81,0.89,22,20,0,22,2
5,finetuned-mistral7b,macro_avg,identity,all,0.64,0.53,0.48,0.47,22,13,7,15,9
5,finetuned-llama8b,macro_avg,identity,all,0.86,0.43,0.50,0.46,22,19,3,19,3
5,finetuned-gemma9b,macro_avg,identity,all,0.84,0.43,0.47,0.45,22,18,3,19,4
5,finetuned-llama3b,macro_avg,identity,all,0.50,0.53,0.57,0.44,22,11,11,11,11

In [11]:
identity_df[identity_df['class'] == '+I'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
6,finetuned-qwen7b,per_class,identity,+I,0.95,1.00,0.95,0.97,19,18,0,3,1
6,finetuned-llama8b,per_class,identity,+I,0.86,0.86,1.00,0.93,19,19,3,0,0
6,finetuned-gemma9b,per_class,identity,+I,0.82,0.86,0.95,0.90,19,18,3,0,1
6,finetuned-mistral7b,per_class,identity,+I,0.64,0.92,0.63,0.75,19,12,1,2,7
6,finetuned-llama3b,per_class,identity,+I,0.50,0.90,0.47,0.62,19,9,1,2,10

In [12]:
identity_df[identity_df['class'] == '-I'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
7,finetuned-qwen7b,per_class,identity,-I,0.95,1.00,0.67,0.80,3,2,0,19,1
7,finetuned-llama3b,per_class,identity,-I,0.50,0.17,0.67,0.27,3,2,10,9,1
7,finetuned-mistral7b,per_class,identity,-I,0.64,0.14,0.33,0.20,3,1,6,13,2
7,finetuned-gemma9b,per_class,identity,-I,0.86,0.00,0.00,0.00,3,0,0,19,3
7,finetuned-llama8b,per_class,identity,-I,0.86,0.00,0.00,0.00,3,0,0,19,3

In [13]:
identity_df['class'].unique()

array(['+I', 'all', '-I'], dtype=object)

---

## Expore Own Identity

In [14]:
own_identity_df = classify_df.query("property == 'own_identity'").sort_values(by='f1_score', ascending=False)
own_identity_df[own_identity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
8,finetuned-qwen7b,macro_avg,own_identity,all,0.75,0.75,0.70,0.72,22,16,5,17,6
8,finetuned-llama8b,macro_avg,own_identity,all,0.59,0.30,0.50,0.37,22,13,9,13,9
8,finetuned-mistral7b,macro_avg,own_identity,all,0.45,0.71,0.48,0.36,22,9,11,11,13
8,finetuned-llama3b,macro_avg,own_identity,all,0.41,0.45,0.48,0.34,22,9,13,9,13
8,finetuned-gemma9b,macro_avg,own_identity,all,0.50,0.47,0.21,0.28,22,4,4,18,18

In [15]:
own_identity_df[own_identity_df['class'] == '+O'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
9,finetuned-qwen7b,per_class,own_identity,+O,0.77,0.79,0.85,0.81,13,11,3,6,2
9,finetuned-llama8b,per_class,own_identity,+O,0.59,0.59,1.00,0.74,13,13,9,0,0
9,finetuned-mistral7b,per_class,own_identity,+O,0.45,1.00,0.08,0.14,13,1,0,9,12
9,finetuned-llama3b,per_class,own_identity,+O,0.41,0.50,0.08,0.13,13,1,1,8,12
9,finetuned-gemma9b,per_class,own_identity,+O,0.36,0.33,0.08,0.12,13,1,2,7,12

In [16]:
own_identity_df[own_identity_df['class'] == '-O'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
10,finetuned-qwen7b,per_class,own_identity,-O,0.73,0.71,0.56,0.63,9,5,2,11,4
10,finetuned-mistral7b,per_class,own_identity,-O,0.45,0.42,0.89,0.57,9,8,11,2,1
10,finetuned-llama3b,per_class,own_identity,-O,0.41,0.40,0.89,0.55,9,8,12,1,1
10,finetuned-gemma9b,per_class,own_identity,-O,0.64,0.60,0.33,0.43,9,3,2,11,6
10,finetuned-llama8b,per_class,own_identity,-O,0.59,0.00,0.00,0.00,9,0,0,13,9

In [17]:
own_identity_df['class'].unique()

array(['+O', 'all', '-O'], dtype=object)

---

## Explore Unity

In [18]:
unity_df = classify_df.query("property == 'unity'").sort_values(by='f1_score', ascending=False)
unity_df[unity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
11,finetuned-gemma9b,macro_avg,unity,all,0.71,0.57,0.66,0.52,22,12,9,35,10
11,finetuned-qwen7b,macro_avg,unity,all,0.74,0.43,0.44,0.43,22,13,8,36,9
11,finetuned-llama3b,macro_avg,unity,all,0.61,0.25,0.27,0.26,22,9,13,31,13
11,finetuned-llama8b,macro_avg,unity,all,0.73,0.20,0.33,0.25,22,13,9,35,9
11,finetuned-mistral7b,macro_avg,unity,all,0.70,0.19,0.28,0.23,22,11,9,35,11

In [19]:
unity_df[unity_df['class'] == '+U'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
12,finetuned-llama8b,per_class,unity,+U,0.59,0.59,1.00,0.74,13,13,9,0,0
12,finetuned-gemma9b,per_class,unity,+U,0.73,1.00,0.54,0.70,13,7,0,9,6
12,finetuned-qwen7b,per_class,unity,+U,0.68,0.80,0.62,0.70,13,8,2,7,5
12,finetuned-mistral7b,per_class,unity,+U,0.55,0.58,0.85,0.69,13,11,8,1,2
12,finetuned-llama3b,per_class,unity,+U,0.45,0.54,0.54,0.54,13,7,6,3,6

In [20]:
unity_df[unity_df['class'] == '-U'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
13,finetuned-qwen7b,per_class,unity,-U,0.68,0.50,0.71,0.59,7,5,5,10,2
13,finetuned-gemma9b,per_class,unity,-U,0.64,0.43,0.43,0.43,7,3,4,11,4
13,finetuned-llama3b,per_class,unity,-U,0.45,0.22,0.29,0.25,7,2,7,8,5
13,finetuned-llama8b,per_class,unity,-U,0.68,0.00,0.00,0.00,7,0,0,15,7
13,finetuned-mistral7b,per_class,unity,-U,0.64,0.00,0.00,0.00,7,0,1,14,7

In [21]:
unity_df[unity_df['class'] == '~U'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
14,finetuned-gemma9b,per_class,unity,~U,0.77,0.29,1.0,0.44,2,2,5,15,0
14,finetuned-llama3b,per_class,unity,~U,0.91,0.00,0.0,0.00,2,0,0,20,2
14,finetuned-llama8b,per_class,unity,~U,0.91,0.00,0.0,0.00,2,0,0,20,2
14,finetuned-qwen7b,per_class,unity,~U,0.86,0.00,0.0,0.00,2,0,1,19,2
14,finetuned-mistral7b,per_class,unity,~U,0.91,0.00,0.0,0.00,2,0,0,20,2

In [22]:
unity_df['class'].unique()

array(['+U', '-U', 'all', '~U'], dtype=object)

---

## Explore Dependence

In [23]:
dependence_df = classify_df.query("property == 'dependence'").sort_values(by='f1_score', ascending=False)
dependence_df[dependence_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
15,finetuned-qwen7b,macro_avg,dependence,all,0.82,0.77,0.64,0.69,22,17,3,19,5
15,finetuned-gemma9b,macro_avg,dependence,all,0.66,0.61,0.62,0.60,22,14,7,15,8
15,finetuned-llama8b,macro_avg,dependence,all,0.77,0.39,0.50,0.44,22,17,5,17,5
15,finetuned-mistral7b,macro_avg,dependence,all,0.73,0.38,0.44,0.41,22,15,5,17,7
15,finetuned-llama3b,macro_avg,dependence,all,0.45,0.33,0.29,0.31,22,10,12,10,12

In [24]:
dependence_df[dependence_df['class'] == '+D'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
16,finetuned-qwen7b,per_class,dependence,+D,0.82,0.67,0.4,0.50,5,2,1,16,3
16,finetuned-gemma9b,per_class,dependence,+D,0.68,0.38,0.6,0.46,5,3,5,12,2
16,finetuned-llama3b,per_class,dependence,+D,0.45,0.00,0.0,0.00,5,0,7,10,5
16,finetuned-llama8b,per_class,dependence,+D,0.77,0.00,0.0,0.00,5,0,0,17,5
16,finetuned-mistral7b,per_class,dependence,+D,0.77,0.00,0.0,0.00,5,0,0,17,5

In [25]:
dependence_df[dependence_df['class'] == '-D'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
17,finetuned-qwen7b,per_class,dependence,-D,0.82,0.88,0.88,0.88,17,15,2,3,2
17,finetuned-llama8b,per_class,dependence,-D,0.77,0.77,1.00,0.87,17,17,5,0,0
17,finetuned-mistral7b,per_class,dependence,-D,0.68,0.75,0.88,0.81,17,15,5,0,2
17,finetuned-gemma9b,per_class,dependence,-D,0.64,0.85,0.65,0.73,17,11,2,3,6
17,finetuned-llama3b,per_class,dependence,-D,0.45,0.67,0.59,0.62,17,10,5,0,7

In [26]:
dependence_df['class'].unique()

array(['-D', 'all', '+D'], dtype=object)

---

## See which properties were most difficult to identify

In [34]:
classify_df[['property', 'f1_score']].sort_values(by='f1_score').drop_duplicates().head(20)

        property  f1_score
13         unity      0.00
4       rigidity      0.00
7       identity      0.00
16    dependence      0.00
10  own_identity      0.00
1       rigidity      0.12
9   own_identity      0.12
9   own_identity      0.13
9   own_identity      0.14
7       identity      0.20
11         unity      0.23
11         unity      0.25
11         unity      0.26
7       identity      0.27
1       rigidity      0.27
8   own_identity      0.28
1       rigidity      0.29
15    dependence      0.31
0            all      0.32
0            all      0.33

In [37]:
classify_df[['class', 'f1_score']].sort_values(by='f1_score').drop_duplicates().head(20)

   class  f1_score
13    -U      0.00
4     ~R      0.00
3     -R      0.00
7     -I      0.00
16    +D      0.00
14    ~U      0.00
10    -O      0.00
1    all      0.12
9     +O      0.12
9     +O      0.13
9     +O      0.14
7     -I      0.20
11   all      0.23
11   all      0.25
13    -U      0.25
11   all      0.26
7     -I      0.27
1    all      0.27
8    all      0.28
1    all      0.29