# Explore Classify DSPy Results
Notebook for exporing the classify results using the DSPy models.
The result are stored in `../output/evaluation_results/`.  
The classify DSPy results contain standard ML metrics such as accuracy, precission, etc.

In [1]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

----

## Load all classifaction results

In [2]:
classify_files = glob.glob('../output/evaluation_results/classify_*dspy_*.csv')
len(classify_files)

52

In [3]:
classify_df = pd.concat([pd.read_csv(file) for file in classify_files])
classify_df.head()

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
0,dspy_gemini_gemma9b,overall,all,all,0.66,0.55,0.55,0.50,110,64,43,111,46
1,dspy_gemini_gemma9b,macro_avg,rigidity,all,0.67,0.61,0.66,0.47,22,11,11,33,11
2,dspy_gemini_gemma9b,per_class,rigidity,+R,0.64,1.00,0.47,0.64,15,7,0,7,8
3,dspy_gemini_gemma9b,per_class,rigidity,-R,0.55,0.09,1.00,0.17,1,1,10,11,0
4,dspy_gemini_gemma9b,per_class,rigidity,~R,0.82,0.75,0.50,0.60,6,3,1,15,3

----

## Explore overall scores

looking at just f1_score, the non-agent large llms w/o dspy do best.

In [4]:
overall_df = classify_df.query("property == 'all'").sort_values(by='f1_score', ascending=False)
overall_df.head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
0,dspy_gemini_mistral-small-3.1,overall,all,all,0.75,0.63,0.69,0.62,110,77,33,121,33
0,dspy_agent_gemini_llama70b,overall,all,all,0.76,0.63,0.66,0.60,110,78,32,122,32
0,dspy_agent_gemini_gemma9b,overall,all,all,0.70,0.64,0.63,0.59,110,69,38,116,41
0,dspy_agent_critic_gemini_llama70b,overall,all,all,0.74,0.61,0.66,0.59,110,76,34,120,34
0,dspy_agent_critic_gemini_gpt4o-mini,overall,all,all,0.73,0.62,0.65,0.58,110,74,36,118,36
0,dspy_gemini_llama8b,overall,all,all,0.76,0.60,0.62,0.58,110,78,31,123,32
0,dspy_gemini_qwen72b,overall,all,all,0.76,0.61,0.62,0.58,110,78,32,122,32
0,dspy_agent_critic_gemini_mistral-small-3.1,overall,all,all,0.72,0.60,0.64,0.58,110,72,35,119,38
0,dspy_agent_gemini_mistral-small-3.1,overall,all,all,0.71,0.61,0.63,0.57,110,72,38,116,38
0,dspy_agent_gemini_qwen72b,overall,all,all,0.74,0.61,0.62,0.57,110,76,34,120,34
0,dspy_agent_critic_claude_qwen72b,overall,all,all,0.70,0.62,0.62,0.56,110,69,39,115,41
0,dspy_gemini_llama70b,overall,all,all,0.73,0.61,0.62,0.56,110,74,36,118,36
0,dspy_agent_critic_gemini_gemma9b,overall,all,all,0.69,0.61,0.59,0.55,110,67,38,116,43
0,dspy_agent_critic_gemini_qwen72b,overall,all,all,0.72,0.56,0.59,0.55,110,73,36,118,37
0,dspy_agent_gemini_gpt4o-mini,overall,all,all,0.69,0.63,0.61,0.55,110,69,41,113,41
0,dspy_agent_claude_llama70b,overall,all,all,0.72,0.55,0.57,0.53,110,73,37,117,37
0,dspy_agent_claude_qwen72b,overall,all,all,0.71,0.57,0.58,0.53,110,72,38,116,38
0,dspy_claude_qwen72b,overall,all,all,0.73,0.57,0.51,0.53,110,74,35,119,36
0,dspy_agent_critic_claude_llama70b,overall,all,all,0.66,0.61,0.63,0.53,110,65,44,110,45
0,dspy_agent_gemini_mistral7b,overall,all,all,0.69,0.57,0.58,0.52,110,67,39,115,43

---

## Expore rigidity  
summary:  
* the gemini-crtic-no-intro had the best overall f1_score for all the rigidity classes (0.91)
* the gemini-crtic-no-intro, anthropic-corrected,  and had the best overall f1_score for +R (1.00)
* the anthropic and gemini critics

In [5]:
rigidity_df = classify_df.query("property == 'rigidity'").sort_values(by='f1_score', ascending=False)
rigidity_df[rigidity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
1,dspy_agent_critic_gemini_gpt4o-mini,macro_avg,rigidity,all,0.85,0.66,0.82,0.66,22,17,5,39,5
1,dspy_agent_critic_gemini_qwen72b,macro_avg,rigidity,all,0.82,0.67,0.83,0.64,22,16,6,38,6
1,dspy_agent_critic_gemini_gemma9b,macro_avg,rigidity,all,0.80,0.68,0.74,0.60,22,15,6,38,7
1,dspy_agent_gemini_mistral7b,macro_avg,rigidity,all,0.76,0.60,0.79,0.59,22,14,8,36,8
1,dspy_gemini_qwen72b,macro_avg,rigidity,all,0.79,0.71,0.74,0.58,22,15,7,37,7
1,dspy_agent_critic_gemini_llama70b,macro_avg,rigidity,all,0.76,0.62,0.79,0.57,22,14,8,36,8
1,dspy_gemini_mistral-small-3.1,macro_avg,rigidity,all,0.79,0.61,0.74,0.57,22,15,7,37,7
1,dspy_agent_critic_gemini_mistral-small-3.1,macro_avg,rigidity,all,0.79,0.56,0.74,0.57,22,15,7,37,7
1,dspy_agent_gemini_qwen72b,macro_avg,rigidity,all,0.76,0.70,0.72,0.56,22,14,8,36,8
1,dspy_gemini_llama70b,macro_avg,rigidity,all,0.76,0.70,0.72,0.56,22,14,8,36,8
1,dspy_agent_gemini_llama70b,macro_avg,rigidity,all,0.76,0.68,0.72,0.55,22,14,8,36,8
1,dspy_agent_critic_gemini_llama8b,macro_avg,rigidity,all,0.77,0.59,0.72,0.54,22,14,7,37,8
1,dspy_agent_gemini_gemma9b,macro_avg,rigidity,all,0.73,0.64,0.73,0.54,22,13,9,35,9
1,dspy_agent_gemini_mistral-small-3.1,macro_avg,rigidity,all,0.79,0.67,0.71,0.54,22,15,7,37,7
1,dspy_agent_critic_claude_llama70b,macro_avg,rigidity,all,0.73,0.60,0.73,0.53,22,13,9,35,9
1,dspy_agent_critic_claude_qwen72b,macro_avg,rigidity,all,0.70,0.63,0.71,0.52,22,12,10,34,10
1,dspy_gemini_llama8b,macro_avg,rigidity,all,0.73,0.55,0.70,0.51,22,13,9,35,9
1,dspy_agent_claude_mistral-small-3.1,macro_avg,rigidity,all,0.73,0.51,0.70,0.50,22,13,9,35,9
1,dspy_claude_mistral-small-3.1,macro_avg,rigidity,all,0.70,0.56,0.71,0.50,22,12,10,34,10
1,dspy_agent_claude_llama70b,macro_avg,rigidity,all,0.73,0.57,0.67,0.48,22,13,9,35,9

In [6]:
rigidity_df[rigidity_df['class'] == '+R'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
2,dspy_agent_critic_gemini_gpt4o-mini,per_class,rigidity,+R,0.82,0.92,0.80,0.86,15,12,1,6,3
2,dspy_gemini_qwen72b,per_class,rigidity,+R,0.82,1.00,0.73,0.85,15,11,0,7,4
2,dspy_agent_gemini_mistral-small-3.1,per_class,rigidity,+R,0.77,0.86,0.80,0.83,15,12,2,5,3
2,dspy_gemini_mistral-small-3.1,per_class,rigidity,+R,0.77,0.92,0.73,0.81,15,11,1,6,4
2,dspy_agent_critic_gemini_mistral-small-3.1,per_class,rigidity,+R,0.77,0.92,0.73,0.81,15,11,1,6,4
2,dspy_agent_gemini_qwen72b,per_class,rigidity,+R,0.77,1.00,0.67,0.80,15,10,0,7,5
2,dspy_agent_critic_gemini_qwen72b,per_class,rigidity,+R,0.77,1.00,0.67,0.80,15,10,0,7,5
2,dspy_gemini_llama70b,per_class,rigidity,+R,0.77,1.00,0.67,0.80,15,10,0,7,5
2,dspy_agent_critic_gemini_llama8b,per_class,rigidity,+R,0.77,1.00,0.67,0.80,15,10,0,7,5
2,dspy_agent_critic_gemini_gemma9b,per_class,rigidity,+R,0.73,0.85,0.73,0.79,15,11,2,5,4
2,dspy_agent_claude_llama70b,per_class,rigidity,+R,0.73,0.91,0.67,0.77,15,10,1,6,5
2,dspy_claude_qwen72b,per_class,rigidity,+R,0.73,0.91,0.67,0.77,15,10,1,6,5
2,dspy_agent_gemini_llama70b,per_class,rigidity,+R,0.73,0.91,0.67,0.77,15,10,1,6,5
2,dspy_gemini_mistral7b,per_class,rigidity,+R,0.68,0.83,0.67,0.74,15,10,2,5,5
2,dspy_agent_claude_mistral-small-3.1,per_class,rigidity,+R,0.68,0.90,0.60,0.72,15,9,1,6,6
2,dspy_gemini_llama8b,per_class,rigidity,+R,0.68,0.90,0.60,0.72,15,9,1,6,6
2,dspy_agent_gemini_gemma9b,per_class,rigidity,+R,0.68,1.00,0.53,0.70,15,8,0,7,7
2,dspy_agent_critic_claude_llama70b,per_class,rigidity,+R,0.68,1.00,0.53,0.70,15,8,0,7,7
2,dspy_agent_gemini_gpt4o-mini,per_class,rigidity,+R,0.68,1.00,0.53,0.70,15,8,0,7,7
2,dspy_agent_gemini_mistral7b,per_class,rigidity,+R,0.68,1.00,0.53,0.70,15,8,0,7,7

In [7]:
rigidity_df[rigidity_df['class'] == '-R'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
3,dspy_agent_gemini_mistral7b,per_class,rigidity,-R,0.91,0.33,1.0,0.50,1,1,2,19,0
3,dspy_agent_critic_gemini_gpt4o-mini,per_class,rigidity,-R,0.86,0.25,1.0,0.40,1,1,3,18,0
3,dspy_agent_critic_gemini_mistral-small-3.1,per_class,rigidity,-R,0.86,0.25,1.0,0.40,1,1,3,18,0
3,dspy_agent_claude_mistral-small-3.1,per_class,rigidity,-R,0.82,0.20,1.0,0.33,1,1,4,17,0
3,dspy_agent_critic_gemini_gemma9b,per_class,rigidity,-R,0.82,0.20,1.0,0.33,1,1,4,17,0
3,dspy_agent_critic_claude_gemma9b,per_class,rigidity,-R,0.82,0.20,1.0,0.33,1,1,4,17,0
3,dspy_agent_gemini_mistral-small-3.1,per_class,rigidity,-R,0.77,0.17,1.0,0.29,1,1,5,16,0
3,dspy_agent_critic_gemini_llama8b,per_class,rigidity,-R,0.77,0.17,1.0,0.29,1,1,5,16,0
3,dspy_gemini_mistral-small-3.1,per_class,rigidity,-R,0.77,0.17,1.0,0.29,1,1,5,16,0
3,dspy_agent_critic_gemini_qwen72b,per_class,rigidity,-R,0.77,0.17,1.0,0.29,1,1,5,16,0
3,dspy_gemini_llama8b,per_class,rigidity,-R,0.73,0.14,1.0,0.25,1,1,6,15,0
3,dspy_agent_critic_gemini_llama70b,per_class,rigidity,-R,0.73,0.14,1.0,0.25,1,1,6,15,0
3,dspy_claude_mistral-small-3.1,per_class,rigidity,-R,0.68,0.12,1.0,0.22,1,1,7,14,0
3,dspy_agent_critic_claude_llama70b,per_class,rigidity,-R,0.68,0.12,1.0,0.22,1,1,7,14,0
3,dspy_agent_gemini_llama70b,per_class,rigidity,-R,0.68,0.12,1.0,0.22,1,1,7,14,0
3,dspy_agent_claude_llama70b,per_class,rigidity,-R,0.68,0.12,1.0,0.22,1,1,7,14,0
3,dspy_gemini_qwen72b,per_class,rigidity,-R,0.68,0.12,1.0,0.22,1,1,7,14,0
3,dspy_claude_llama8b,per_class,rigidity,-R,0.68,0.12,1.0,0.22,1,1,7,14,0
3,dspy_agent_claude_gemma9b,per_class,rigidity,-R,0.64,0.11,1.0,0.20,1,1,8,13,0
3,dspy_gemini_llama70b,per_class,rigidity,-R,0.64,0.11,1.0,0.20,1,1,8,13,0

In [8]:
rigidity_df[rigidity_df['class'] == '~R'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
4,dspy_agent_critic_gemini_qwen72b,per_class,rigidity,~R,0.91,0.83,0.83,0.83,6,5,1,15,1
4,dspy_gemini_gpt4o-mini,per_class,rigidity,~R,0.91,1.00,0.67,0.80,6,4,0,16,2
4,dspy_agent_critic_gemini_llama70b,per_class,rigidity,~R,0.86,0.71,0.83,0.77,6,5,2,14,1
4,dspy_agent_critic_gemini_gpt4o-mini,per_class,rigidity,~R,0.86,0.80,0.67,0.73,6,4,1,15,2
4,dspy_agent_critic_claude_qwen72b,per_class,rigidity,~R,0.86,0.80,0.67,0.73,6,4,1,15,2
4,dspy_agent_gemini_gemma9b,per_class,rigidity,~R,0.86,0.80,0.67,0.73,6,4,1,15,2
4,dspy_agent_critic_claude_mistral-small-3.1,per_class,rigidity,~R,0.82,0.62,0.83,0.71,6,5,3,13,1
4,dspy_gemini_llama70b,per_class,rigidity,~R,0.86,1.00,0.50,0.67,6,3,0,16,3
4,dspy_agent_critic_claude_llama70b,per_class,rigidity,~R,0.82,0.67,0.67,0.67,6,4,2,14,2
4,dspy_agent_gemini_qwen72b,per_class,rigidity,~R,0.86,1.00,0.50,0.67,6,3,0,16,3
4,dspy_agent_gemini_llama70b,per_class,rigidity,~R,0.86,1.00,0.50,0.67,6,3,0,16,3
4,dspy_agent_critic_gemini_gemma9b,per_class,rigidity,~R,0.86,1.00,0.50,0.67,6,3,0,16,3
4,dspy_claude_mistral-small-3.1,per_class,rigidity,~R,0.82,0.67,0.67,0.67,6,4,2,14,2
4,dspy_gemini_qwen72b,per_class,rigidity,~R,0.86,1.00,0.50,0.67,6,3,0,16,3
4,dspy_agent_gemini_llama3b,per_class,rigidity,~R,0.82,0.75,0.50,0.60,6,3,1,15,3
4,dspy_agent_claude_llama8b,per_class,rigidity,~R,0.82,0.75,0.50,0.60,6,3,1,15,3
4,dspy_gemini_gemma9b,per_class,rigidity,~R,0.82,0.75,0.50,0.60,6,3,1,15,3
4,dspy_gemini_mistral-small-3.1,per_class,rigidity,~R,0.82,0.75,0.50,0.60,6,3,1,15,3
4,dspy_agent_gemini_mistral7b,per_class,rigidity,~R,0.68,0.45,0.83,0.59,6,5,6,10,1
4,dspy_agent_critic_gemini_llama3b,per_class,rigidity,~R,0.77,0.60,0.50,0.55,6,3,2,14,3

In [9]:
rigidity_df['class'].unique()

array(['+R', '~R', 'all', '-R'], dtype=object)

---

## Explore Identity

In [10]:
identity_df = classify_df.query("property == 'identity'").sort_values(by='f1_score', ascending=False)
identity_df[identity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
5,dspy_agent_claude_qwen72b,macro_avg,identity,all,0.86,0.72,0.78,0.75,22,19,3,19,3
5,dspy_claude_gpt4o-mini,macro_avg,identity,all,0.91,0.95,0.67,0.73,22,20,2,20,2
5,dspy_gemini_llama3b,macro_avg,identity,all,0.91,0.95,0.67,0.73,22,20,2,20,2
5,dspy_claude_qwen7b,macro_avg,identity,all,0.91,0.95,0.67,0.73,22,20,2,20,2
5,dspy_agent_critic_gemini_qwen7b,macro_avg,identity,all,0.77,0.71,0.68,0.68,22,15,3,19,7
5,dspy_gemini_llama8b,macro_avg,identity,all,0.86,0.70,0.64,0.66,22,19,3,19,3
5,dspy_agent_gemini_llama70b,macro_avg,identity,all,0.77,0.64,0.73,0.65,22,17,5,17,5
5,dspy_gemini_mistral7b,macro_avg,identity,all,0.82,0.69,0.59,0.63,22,17,3,19,5
5,dspy_claude_gemma9b,macro_avg,identity,all,0.73,0.61,0.70,0.61,22,16,6,16,6
5,dspy_claude_llama70b,macro_avg,identity,all,0.82,0.61,0.61,0.61,22,18,4,18,4
5,dspy_claude_qwen72b,macro_avg,identity,all,0.82,0.61,0.61,0.61,22,18,4,18,4
5,dspy_agent_critic_gemini_llama70b,macro_avg,identity,all,0.73,0.61,0.70,0.61,22,16,6,16,6
5,dspy_gemini_mistral-small-3.1,macro_avg,identity,all,0.73,0.61,0.70,0.61,22,16,6,16,6
5,dspy_agent_claude_qwen7b,macro_avg,identity,all,0.77,0.69,0.54,0.60,22,15,3,19,7
5,dspy_claude_mistral-small-3.1,macro_avg,identity,all,0.68,0.59,0.68,0.58,22,15,7,15,7
5,dspy_gemini_llama70b,macro_avg,identity,all,0.77,0.57,0.59,0.58,22,17,5,17,5
5,dspy_gemini_qwen72b,macro_avg,identity,all,0.77,0.57,0.59,0.58,22,17,5,17,5
5,dspy_gemini_gemma9b,macro_avg,identity,all,0.77,0.57,0.59,0.58,22,17,5,17,5
5,dspy_agent_claude_llama70b,macro_avg,identity,all,0.77,0.57,0.59,0.58,22,17,5,17,5
5,dspy_agent_gemini_qwen7b,macro_avg,identity,all,0.77,0.61,0.56,0.58,22,16,4,18,6

In [11]:
identity_df[identity_df['class'] == '+I'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
6,dspy_gemini_llama3b,per_class,identity,+I,0.91,0.90,1.00,0.95,19,19,2,1,0
6,dspy_claude_gpt4o-mini,per_class,identity,+I,0.91,0.90,1.00,0.95,19,19,2,1,0
6,dspy_claude_qwen7b,per_class,identity,+I,0.91,0.90,1.00,0.95,19,19,2,1,0
6,dspy_gemini_qwen7b,per_class,identity,+I,0.86,0.90,0.95,0.92,19,18,2,1,1
6,dspy_gemini_llama8b,per_class,identity,+I,0.86,0.90,0.95,0.92,19,18,2,1,1
6,dspy_agent_claude_qwen72b,per_class,identity,+I,0.86,0.94,0.89,0.92,19,17,1,2,2
6,dspy_claude_llama70b,per_class,identity,+I,0.82,0.89,0.89,0.89,19,17,2,1,2
6,dspy_claude_qwen72b,per_class,identity,+I,0.82,0.89,0.89,0.89,19,17,2,1,2
6,dspy_claude_llama3b,per_class,identity,+I,0.77,0.85,0.89,0.87,19,17,3,0,2
6,dspy_gemini_qwen72b,per_class,identity,+I,0.77,0.89,0.84,0.86,19,16,2,1,3
6,dspy_agent_gemini_llama70b,per_class,identity,+I,0.77,0.94,0.79,0.86,19,15,1,2,4
6,dspy_gemini_gemma9b,per_class,identity,+I,0.77,0.89,0.84,0.86,19,16,2,1,3
6,dspy_gemini_llama70b,per_class,identity,+I,0.77,0.89,0.84,0.86,19,16,2,1,3
6,dspy_agent_claude_llama70b,per_class,identity,+I,0.77,0.89,0.84,0.86,19,16,2,1,3
6,dspy_gemini_mistral7b,per_class,identity,+I,0.77,0.89,0.84,0.86,19,16,2,1,3
6,dspy_gemini_gpt4o-mini,per_class,identity,+I,0.73,0.88,0.79,0.83,19,15,2,1,4
6,dspy_agent_critic_gemini_qwen72b,per_class,identity,+I,0.73,0.88,0.79,0.83,19,15,2,1,4
6,dspy_agent_gemini_qwen72b,per_class,identity,+I,0.73,0.88,0.79,0.83,19,15,2,1,4
6,dspy_agent_gemini_qwen7b,per_class,identity,+I,0.73,0.88,0.79,0.83,19,15,2,1,4
6,dspy_claude_gemma9b,per_class,identity,+I,0.73,0.93,0.74,0.82,19,14,1,2,5

In [12]:
identity_df[identity_df['class'] == '-I'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
7,dspy_agent_claude_qwen72b,per_class,identity,-I,0.86,0.50,0.67,0.57,3,2,2,17,1
7,dspy_agent_critic_gemini_qwen7b,per_class,identity,-I,0.86,0.50,0.67,0.57,3,2,2,17,1
7,dspy_claude_qwen7b,per_class,identity,-I,0.91,1.00,0.33,0.50,3,1,0,19,2
7,dspy_gemini_llama3b,per_class,identity,-I,0.91,1.00,0.33,0.50,3,1,0,19,2
7,dspy_claude_gpt4o-mini,per_class,identity,-I,0.91,1.00,0.33,0.50,3,1,0,19,2
7,dspy_agent_gemini_llama70b,per_class,identity,-I,0.77,0.33,0.67,0.44,3,2,4,15,1
7,dspy_gemini_llama8b,per_class,identity,-I,0.86,0.50,0.33,0.40,3,1,1,18,2
7,dspy_gemini_mistral-small-3.1,per_class,identity,-I,0.73,0.29,0.67,0.40,3,2,5,14,1
7,dspy_claude_gemma9b,per_class,identity,-I,0.73,0.29,0.67,0.40,3,2,5,14,1
7,dspy_agent_critic_gemini_llama70b,per_class,identity,-I,0.73,0.29,0.67,0.40,3,2,5,14,1
7,dspy_agent_claude_qwen7b,per_class,identity,-I,0.86,0.50,0.33,0.40,3,1,1,18,2
7,dspy_gemini_mistral7b,per_class,identity,-I,0.86,0.50,0.33,0.40,3,1,1,18,2
7,dspy_agent_critic_claude_llama8b,per_class,identity,-I,0.59,0.25,1.00,0.40,3,3,9,10,0
7,dspy_agent_critic_claude_llama70b,per_class,identity,-I,0.55,0.23,1.00,0.38,3,3,10,9,0
7,dspy_claude_mistral-small-3.1,per_class,identity,-I,0.68,0.25,0.67,0.36,3,2,6,13,1
7,dspy_agent_claude_gpt4o-mini,per_class,identity,-I,0.68,0.25,0.67,0.36,3,2,6,13,1
7,dspy_agent_critic_gemini_gemma9b,per_class,identity,-I,0.68,0.25,0.67,0.36,3,2,6,13,1
7,dspy_agent_critic_claude_qwen72b,per_class,identity,-I,0.68,0.25,0.67,0.36,3,2,6,13,1
7,dspy_agent_gemini_gemma9b,per_class,identity,-I,0.64,0.22,0.67,0.33,3,2,7,12,1
7,dspy_agent_critic_claude_qwen7b,per_class,identity,-I,0.64,0.22,0.67,0.33,3,2,7,12,1

In [13]:
identity_df['class'].unique()

array(['+I', 'all', '-I'], dtype=object)

---

## Expore Own Identity

In [14]:
own_identity_df = classify_df.query("property == 'own_identity'").sort_values(by='f1_score', ascending=False)
own_identity_df[own_identity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
8,dspy_agent_critic_gemini_llama70b,macro_avg,own_identity,all,0.73,0.80,0.77,0.72,22,16,6,16,6
8,dspy_agent_critic_claude_qwen72b,macro_avg,own_identity,all,0.73,0.80,0.77,0.72,22,16,6,16,6
8,dspy_agent_critic_gemini_mistral-small-3.1,macro_avg,own_identity,all,0.73,0.77,0.71,0.71,22,15,5,17,7
8,dspy_claude_qwen7b,macro_avg,own_identity,all,0.68,0.69,0.70,0.68,22,15,7,15,7
8,dspy_claude_qwen72b,macro_avg,own_identity,all,0.68,0.69,0.70,0.68,22,15,7,15,7
8,dspy_agent_claude_llama70b,macro_avg,own_identity,all,0.68,0.68,0.68,0.68,22,15,7,15,7
8,dspy_agent_claude_qwen72b,macro_avg,own_identity,all,0.68,0.68,0.68,0.68,22,15,7,15,7
8,dspy_agent_critic_claude_llama70b,macro_avg,own_identity,all,0.68,0.78,0.73,0.68,22,15,7,15,7
8,dspy_agent_gemini_mistral-small-3.1,macro_avg,own_identity,all,0.68,0.72,0.71,0.68,22,15,7,15,7
8,dspy_agent_gemini_qwen72b,macro_avg,own_identity,all,0.68,0.69,0.70,0.68,22,15,7,15,7
8,dspy_agent_gemini_llama70b,macro_avg,own_identity,all,0.68,0.72,0.71,0.68,22,15,7,15,7
8,dspy_gemini_llama8b,macro_avg,own_identity,all,0.68,0.67,0.66,0.66,22,15,7,15,7
8,dspy_gemini_mistral7b,macro_avg,own_identity,all,0.64,0.66,0.66,0.64,22,14,8,14,8
8,dspy_agent_gemini_gemma9b,macro_avg,own_identity,all,0.64,0.66,0.66,0.64,22,14,8,14,8
8,dspy_gemini_mistral-small-3.1,macro_avg,own_identity,all,0.64,0.64,0.64,0.63,22,14,8,14,8
8,dspy_agent_critic_gemini_gemma9b,macro_avg,own_identity,all,0.64,0.70,0.68,0.63,22,14,8,14,8
8,dspy_gemini_qwen72b,macro_avg,own_identity,all,0.64,0.62,0.62,0.62,22,14,8,14,8
8,dspy_agent_critic_gemini_gpt4o-mini,macro_avg,own_identity,all,0.64,0.76,0.69,0.62,22,14,8,14,8
8,dspy_agent_critic_gemini_qwen72b,macro_avg,own_identity,all,0.61,0.61,0.59,0.60,22,13,8,14,9
8,dspy_claude_llama3b,macro_avg,own_identity,all,0.59,0.62,0.62,0.59,22,13,9,13,9

In [15]:
own_identity_df[own_identity_df['class'] == '+O'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
9,dspy_gemini_llama8b,per_class,own_identity,+O,0.68,0.71,0.77,0.74,13,10,4,5,3
9,dspy_agent_claude_llama70b,per_class,own_identity,+O,0.68,0.75,0.69,0.72,13,9,3,6,4
9,dspy_agent_claude_qwen72b,per_class,own_identity,+O,0.68,0.75,0.69,0.72,13,9,3,6,4
9,dspy_agent_critic_gemini_llama70b,per_class,own_identity,+O,0.73,1.00,0.54,0.70,13,7,0,9,6
9,dspy_agent_critic_claude_qwen72b,per_class,own_identity,+O,0.73,1.00,0.54,0.70,13,7,0,9,6
9,dspy_claude_qwen72b,per_class,own_identity,+O,0.68,0.80,0.62,0.70,13,8,2,7,5
9,dspy_claude_qwen7b,per_class,own_identity,+O,0.68,0.80,0.62,0.70,13,8,2,7,5
9,dspy_agent_gemini_qwen72b,per_class,own_identity,+O,0.68,0.80,0.62,0.70,13,8,2,7,5
9,dspy_gemini_qwen72b,per_class,own_identity,+O,0.64,0.69,0.69,0.69,13,9,4,5,4
9,dspy_agent_gemini_llama70b,per_class,own_identity,+O,0.68,0.88,0.54,0.67,13,7,1,8,6
9,dspy_agent_critic_gemini_mistral-small-3.1,per_class,own_identity,+O,0.68,0.88,0.54,0.67,13,7,1,8,6
9,dspy_agent_gemini_mistral-small-3.1,per_class,own_identity,+O,0.68,0.88,0.54,0.67,13,7,1,8,6
9,dspy_agent_critic_gemini_qwen72b,per_class,own_identity,+O,0.64,0.73,0.62,0.67,13,8,3,6,5
9,dspy_gemini_mistral-small-3.1,per_class,own_identity,+O,0.64,0.73,0.62,0.67,13,8,3,6,5
9,dspy_agent_gemini_gemma9b,per_class,own_identity,+O,0.64,0.78,0.54,0.64,13,7,2,7,6
9,dspy_gemini_mistral7b,per_class,own_identity,+O,0.64,0.78,0.54,0.64,13,7,2,7,6
9,dspy_agent_critic_claude_llama70b,per_class,own_identity,+O,0.68,1.00,0.46,0.63,13,6,0,9,7
9,dspy_agent_critic_gemini_gemma9b,per_class,own_identity,+O,0.64,0.86,0.46,0.60,13,6,1,8,7
9,dspy_agent_claude_gpt4o-mini,per_class,own_identity,+O,0.59,0.75,0.46,0.57,13,6,2,7,7
9,dspy_claude_llama3b,per_class,own_identity,+O,0.59,0.75,0.46,0.57,13,6,2,7,7

In [16]:
own_identity_df[own_identity_df['class'] == '-O'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
10,dspy_agent_critic_gemini_mistral-small-3.1,per_class,own_identity,-O,0.77,0.67,0.89,0.76,9,8,4,9,1
10,dspy_agent_critic_gemini_llama70b,per_class,own_identity,-O,0.73,0.60,1.00,0.75,9,9,6,7,0
10,dspy_agent_critic_claude_qwen72b,per_class,own_identity,-O,0.73,0.60,1.00,0.75,9,9,6,7,0
10,dspy_agent_critic_claude_llama70b,per_class,own_identity,-O,0.68,0.56,1.00,0.72,9,9,7,6,0
10,dspy_agent_critic_gemini_qwen7b,per_class,own_identity,-O,0.73,0.64,0.78,0.70,9,7,4,9,2
10,dspy_agent_gemini_mistral-small-3.1,per_class,own_identity,-O,0.68,0.57,0.89,0.70,9,8,6,7,1
10,dspy_agent_gemini_qwen7b,per_class,own_identity,-O,0.73,0.64,0.78,0.70,9,7,4,9,2
10,dspy_agent_gemini_llama70b,per_class,own_identity,-O,0.68,0.57,0.89,0.70,9,8,6,7,1
10,dspy_agent_critic_gemini_gpt4o-mini,per_class,own_identity,-O,0.64,0.53,1.00,0.69,9,9,8,5,0
10,dspy_claude_qwen7b,per_class,own_identity,-O,0.68,0.58,0.78,0.67,9,7,5,8,2
10,dspy_agent_critic_claude_qwen7b,per_class,own_identity,-O,0.64,0.53,0.89,0.67,9,8,7,6,1
10,dspy_agent_critic_gemini_gemma9b,per_class,own_identity,-O,0.64,0.53,0.89,0.67,9,8,7,6,1
10,dspy_claude_qwen72b,per_class,own_identity,-O,0.68,0.58,0.78,0.67,9,7,5,8,2
10,dspy_agent_gemini_qwen72b,per_class,own_identity,-O,0.68,0.58,0.78,0.67,9,7,5,8,2
10,dspy_agent_gemini_gemma9b,per_class,own_identity,-O,0.64,0.54,0.78,0.64,9,7,6,7,2
10,dspy_gemini_llama70b,per_class,own_identity,-O,0.59,0.50,0.89,0.64,9,8,8,5,1
10,dspy_claude_llama70b,per_class,own_identity,-O,0.59,0.50,0.89,0.64,9,8,8,5,1
10,dspy_gemini_gemma9b,per_class,own_identity,-O,0.59,0.50,0.89,0.64,9,8,8,5,1
10,dspy_agent_gemini_gpt4o-mini,per_class,own_identity,-O,0.59,0.50,0.89,0.64,9,8,8,5,1
10,dspy_gemini_mistral7b,per_class,own_identity,-O,0.64,0.54,0.78,0.64,9,7,6,7,2

In [17]:
own_identity_df['class'].unique()

array(['-O', '+O', 'all'], dtype=object)

---

## Explore Unity

In [18]:
unity_df = classify_df.query("property == 'unity'").sort_values(by='f1_score', ascending=False)
unity_df[unity_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
11,dspy_agent_critic_gemini_qwen7b,macro_avg,unity,all,0.82,0.80,0.59,0.66,22,15,5,39,7
11,dspy_agent_claude_mistral7b,macro_avg,unity,all,0.85,0.70,0.62,0.64,22,16,4,40,6
11,dspy_gemini_mistral-small-3.1,macro_avg,unity,all,0.85,0.65,0.64,0.62,22,17,5,39,5
11,dspy_claude_gemma9b,macro_avg,unity,all,0.82,0.62,0.62,0.59,22,16,6,38,6
11,dspy_agent_claude_gpt4o-mini,macro_avg,unity,all,0.79,0.56,0.59,0.57,22,15,7,37,7
11,dspy_claude_mistral7b,macro_avg,unity,all,0.85,0.57,0.52,0.52,22,17,5,39,5
11,dspy_agent_gemini_qwen72b,macro_avg,unity,all,0.82,0.49,0.48,0.48,22,16,6,38,6
11,dspy_agent_gemini_llama70b,macro_avg,unity,all,0.82,0.49,0.48,0.48,22,16,6,38,6
11,dspy_gemini_gpt4o-mini,macro_avg,unity,all,0.82,0.46,0.50,0.48,22,16,6,38,6
11,dspy_claude_mistral-small-3.1,macro_avg,unity,all,0.82,0.47,0.48,0.47,22,16,6,38,6
11,dspy_claude_qwen7b,macro_avg,unity,all,0.82,0.56,0.48,0.47,22,16,6,38,6
11,dspy_gemini_qwen72b,macro_avg,unity,all,0.82,0.50,0.48,0.47,22,16,6,38,6
11,dspy_agent_claude_llama3b,macro_avg,unity,all,0.76,0.65,0.52,0.46,22,14,8,36,8
11,dspy_agent_critic_claude_llama3b,macro_avg,unity,all,0.67,0.65,0.61,0.46,22,11,11,33,11
11,dspy_gemini_gemma9b,macro_avg,unity,all,0.74,0.47,0.50,0.46,22,13,8,36,9
11,dspy_gemini_llama3b,macro_avg,unity,all,0.82,0.45,0.48,0.46,22,16,6,38,6
11,dspy_agent_claude_qwen72b,macro_avg,unity,all,0.79,0.45,0.45,0.45,22,15,7,37,7
11,dspy_agent_critic_claude_gpt4o-mini,macro_avg,unity,all,0.67,0.54,0.53,0.45,22,11,11,33,11
11,dspy_agent_gemini_qwen7b,macro_avg,unity,all,0.80,0.43,0.45,0.44,22,15,6,38,7
11,dspy_claude_llama70b,macro_avg,unity,all,0.79,0.45,0.45,0.44,22,15,7,37,7

In [19]:
unity_df[unity_df['class'] == '+U'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
12,dspy_agent_gemini_llama70b,per_class,unity,+U,0.91,0.87,1.00,0.93,13,13,2,7,0
12,dspy_gemini_mistral-small-3.1,per_class,unity,+U,0.91,0.87,1.00,0.93,13,13,2,7,0
12,dspy_agent_gemini_qwen72b,per_class,unity,+U,0.91,0.87,1.00,0.93,13,13,2,7,0
12,dspy_gemini_llama70b,per_class,unity,+U,0.86,0.81,1.00,0.90,13,13,3,6,0
12,dspy_claude_mistral-small-3.1,per_class,unity,+U,0.86,0.81,1.00,0.90,13,13,3,6,0
12,dspy_claude_qwen72b,per_class,unity,+U,0.86,0.81,1.00,0.90,13,13,3,6,0
12,dspy_agent_claude_qwen72b,per_class,unity,+U,0.86,0.86,0.92,0.89,13,12,2,7,1
12,dspy_agent_claude_mistral7b,per_class,unity,+U,0.86,0.86,0.92,0.89,13,12,2,7,1
12,dspy_claude_gemma9b,per_class,unity,+U,0.86,0.86,0.92,0.89,13,12,2,7,1
12,dspy_gemini_llama3b,per_class,unity,+U,0.82,0.76,1.00,0.87,13,13,4,5,0
12,dspy_agent_claude_qwen7b,per_class,unity,+U,0.82,0.76,1.00,0.87,13,13,4,5,0
12,dspy_gemini_qwen72b,per_class,unity,+U,0.82,0.76,1.00,0.87,13,13,4,5,0
12,dspy_agent_gemini_mistral7b,per_class,unity,+U,0.82,0.80,0.92,0.86,13,12,3,6,1
12,dspy_gemini_gpt4o-mini,per_class,unity,+U,0.82,0.80,0.92,0.86,13,12,3,6,1
12,dspy_agent_gemini_qwen7b,per_class,unity,+U,0.82,0.80,0.92,0.86,13,12,3,6,1
12,dspy_agent_claude_gpt4o-mini,per_class,unity,+U,0.82,0.85,0.85,0.85,13,11,2,7,2
12,dspy_agent_critic_gemini_qwen72b,per_class,unity,+U,0.82,0.85,0.85,0.85,13,11,2,7,2
12,dspy_agent_critic_gemini_llama70b,per_class,unity,+U,0.82,0.85,0.85,0.85,13,11,2,7,2
12,dspy_gemini_qwen7b,per_class,unity,+U,0.77,0.72,1.00,0.84,13,13,5,4,0
12,dspy_claude_mistral7b,per_class,unity,+U,0.77,0.72,1.00,0.84,13,13,5,4,0

In [20]:
unity_df[unity_df['class'] == '-U'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
13,dspy_claude_mistral7b,per_class,unity,-U,0.86,1.00,0.57,0.73,7,4,0,15,3
13,dspy_claude_qwen7b,per_class,unity,-U,0.82,1.00,0.43,0.60,7,3,0,15,4
13,dspy_gemini_gpt4o-mini,per_class,unity,-U,0.73,0.57,0.57,0.57,7,4,3,12,3
13,dspy_agent_critic_claude_gpt4o-mini,per_class,unity,-U,0.64,0.45,0.71,0.56,7,5,6,9,2
13,dspy_agent_claude_mistral7b,per_class,unity,-U,0.77,0.75,0.43,0.55,7,3,1,14,4
13,dspy_gemini_mistral-small-3.1,per_class,unity,-U,0.77,0.75,0.43,0.55,7,3,1,14,4
13,dspy_claude_gemma9b,per_class,unity,-U,0.77,0.75,0.43,0.55,7,3,1,14,4
13,dspy_gemini_qwen72b,per_class,unity,-U,0.77,0.75,0.43,0.55,7,3,1,14,4
13,dspy_agent_critic_gemini_mistral-small-3.1,per_class,unity,-U,0.59,0.42,0.71,0.53,7,5,7,8,2
13,dspy_agent_gemini_llama70b,per_class,unity,-U,0.73,0.60,0.43,0.50,7,3,2,13,4
13,dspy_claude_llama70b,per_class,unity,-U,0.73,0.60,0.43,0.50,7,3,2,13,4
13,dspy_gemini_llama3b,per_class,unity,-U,0.73,0.60,0.43,0.50,7,3,2,13,4
13,dspy_agent_critic_gemini_qwen7b,per_class,unity,-U,0.73,0.60,0.43,0.50,7,3,2,13,4
13,dspy_agent_critic_claude_llama70b,per_class,unity,-U,0.55,0.38,0.71,0.50,7,5,8,7,2
13,dspy_agent_gemini_qwen72b,per_class,unity,-U,0.73,0.60,0.43,0.50,7,3,2,13,4
13,dspy_claude_llama3b,per_class,unity,-U,0.64,0.44,0.57,0.50,7,4,5,10,3
13,dspy_claude_mistral-small-3.1,per_class,unity,-U,0.73,0.60,0.43,0.50,7,3,2,13,4
13,dspy_agent_critic_claude_gemma9b,per_class,unity,-U,0.68,0.50,0.43,0.46,7,3,3,12,4
13,dspy_agent_critic_gemini_qwen72b,per_class,unity,-U,0.68,0.50,0.43,0.46,7,3,3,12,4
13,dspy_agent_claude_qwen72b,per_class,unity,-U,0.68,0.50,0.43,0.46,7,3,3,12,4

In [21]:
unity_df[unity_df['class'] == '~U'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
14,dspy_agent_critic_gemini_qwen7b,per_class,unity,~U,0.95,1.00,0.5,0.67,2,1,0,20,1
14,dspy_agent_claude_mistral7b,per_class,unity,~U,0.91,0.50,0.5,0.50,2,1,1,19,1
14,dspy_agent_gemini_llama3b,per_class,unity,~U,0.77,0.29,1.0,0.44,2,2,5,15,0
14,dspy_agent_gemini_llama8b,per_class,unity,~U,0.73,0.25,1.0,0.40,2,2,6,14,0
14,dspy_agent_claude_gpt4o-mini,per_class,unity,~U,0.86,0.33,0.5,0.40,2,1,2,18,1
14,dspy_gemini_mistral-small-3.1,per_class,unity,~U,0.86,0.33,0.5,0.40,2,1,2,18,1
14,dspy_gemini_gemma9b,per_class,unity,~U,0.86,0.33,0.5,0.40,2,1,2,18,1
14,dspy_claude_gemma9b,per_class,unity,~U,0.82,0.25,0.5,0.33,2,1,3,17,1
14,dspy_agent_claude_llama3b,per_class,unity,~U,0.82,0.25,0.5,0.33,2,1,3,17,1
14,dspy_agent_critic_claude_llama3b,per_class,unity,~U,0.59,0.18,1.0,0.31,2,2,9,11,0
14,dspy_agent_critic_claude_gpt4o-mini,per_class,unity,~U,0.73,0.17,0.5,0.25,2,1,5,15,1
14,dspy_agent_critic_gemini_llama8b,per_class,unity,~U,0.73,0.17,0.5,0.25,2,1,5,15,1
14,dspy_agent_critic_gemini_llama3b,per_class,unity,~U,0.59,0.11,0.5,0.18,2,1,8,12,1
14,dspy_agent_critic_claude_qwen7b,per_class,unity,~U,0.59,0.11,0.5,0.18,2,1,8,12,1
14,dspy_agent_critic_claude_mistral-small-3.1,per_class,unity,~U,0.36,0.07,0.5,0.12,2,1,13,7,1
14,dspy_agent_gemini_mistral-small-3.1,per_class,unity,~U,0.77,0.00,0.0,0.00,2,0,3,17,2
14,dspy_agent_gemini_gpt4o-mini,per_class,unity,~U,0.77,0.00,0.0,0.00,2,0,3,17,2
14,dspy_agent_claude_qwen72b,per_class,unity,~U,0.82,0.00,0.0,0.00,2,0,2,18,2
14,dspy_agent_critic_claude_gemma9b,per_class,unity,~U,0.59,0.00,0.0,0.00,2,0,7,13,2
14,dspy_claude_llama8b,per_class,unity,~U,0.77,0.00,0.0,0.00,2,0,3,17,2

In [22]:
unity_df['class'].unique()

array(['+U', '-U', '~U', 'all'], dtype=object)

---

## Explore Dependence

In [23]:
dependence_df = classify_df.query("property == 'dependence'").sort_values(by='f1_score', ascending=False)
dependence_df[dependence_df['class'] == 'all'].head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
15,dspy_agent_gemini_gemma9b,macro_avg,dependence,all,0.89,0.97,0.81,0.88,22,18,1,21,4
15,dspy_agent_gemini_gpt4o-mini,macro_avg,dependence,all,0.86,0.82,0.77,0.79,22,19,3,19,3
15,dspy_agent_critic_claude_gemma9b,macro_avg,dependence,all,0.80,0.74,0.71,0.72,22,17,4,18,5
15,dspy_gemini_llama8b,macro_avg,dependence,all,0.80,0.72,0.71,0.71,22,17,4,18,5
15,dspy_agent_critic_gemini_gpt4o-mini,macro_avg,dependence,all,0.77,0.69,0.71,0.70,22,17,5,17,5
15,dspy_agent_gemini_mistral-small-3.1,macro_avg,dependence,all,0.77,0.69,0.71,0.70,22,17,5,17,5
15,dspy_agent_critic_gemini_mistral-small-3.1,macro_avg,dependence,all,0.75,0.68,0.68,0.68,22,16,5,17,6
15,dspy_gemini_qwen72b,macro_avg,dependence,all,0.73,0.65,0.68,0.66,22,16,6,16,6
15,dspy_agent_gemini_llama70b,macro_avg,dependence,all,0.73,0.65,0.68,0.66,22,16,6,16,6
15,dspy_gemini_llama70b,macro_avg,dependence,all,0.68,0.66,0.72,0.65,22,15,7,15,7
15,dspy_gemini_mistral-small-3.1,macro_avg,dependence,all,0.68,0.66,0.72,0.65,22,15,7,15,7
15,dspy_agent_critic_gemini_gemma9b,macro_avg,dependence,all,0.75,0.74,0.58,0.64,22,15,4,18,7
15,dspy_agent_gemini_qwen72b,macro_avg,dependence,all,0.68,0.62,0.65,0.62,22,15,7,15,7
15,dspy_agent_critic_gemini_llama70b,macro_avg,dependence,all,0.73,0.61,0.61,0.61,22,16,6,16,6
15,dspy_agent_critic_claude_qwen72b,macro_avg,dependence,all,0.73,0.61,0.61,0.61,22,16,6,16,6
15,dspy_agent_critic_claude_gpt4o-mini,macro_avg,dependence,all,0.66,0.61,0.62,0.60,22,14,7,15,8
15,dspy_agent_gemini_llama8b,macro_avg,dependence,all,0.70,0.60,0.58,0.59,22,15,6,16,7
15,dspy_agent_critic_claude_mistral-small-3.1,macro_avg,dependence,all,0.70,0.61,0.58,0.59,22,15,6,16,7
15,dspy_agent_critic_claude_llama70b,macro_avg,dependence,all,0.68,0.57,0.58,0.58,22,15,7,15,7
15,dspy_gemini_qwen7b,macro_avg,dependence,all,0.68,0.57,0.58,0.58,22,15,7,15,7

In [24]:
dependence_df[dependence_df['class'] == '+D'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
16,dspy_agent_gemini_gemma9b,per_class,dependence,+D,0.95,1.00,0.8,0.89,5,4,0,17,1
16,dspy_agent_gemini_gpt4o-mini,per_class,dependence,+D,0.86,0.75,0.6,0.67,5,3,1,16,2
16,dspy_agent_critic_claude_gemma9b,per_class,dependence,+D,0.82,0.60,0.6,0.60,5,3,2,15,2
16,dspy_agent_critic_gemini_mistral-small-3.1,per_class,dependence,+D,0.77,0.50,0.6,0.55,5,3,3,14,2
16,dspy_agent_gemini_mistral-small-3.1,per_class,dependence,+D,0.77,0.50,0.6,0.55,5,3,3,14,2
16,dspy_gemini_llama8b,per_class,dependence,+D,0.77,0.50,0.6,0.55,5,3,3,14,2
16,dspy_agent_critic_gemini_gpt4o-mini,per_class,dependence,+D,0.77,0.50,0.6,0.55,5,3,3,14,2
16,dspy_gemini_llama70b,per_class,dependence,+D,0.68,0.40,0.8,0.53,5,4,6,11,1
16,dspy_gemini_mistral-small-3.1,per_class,dependence,+D,0.68,0.40,0.8,0.53,5,4,6,11,1
16,dspy_agent_gemini_llama70b,per_class,dependence,+D,0.73,0.43,0.6,0.50,5,3,4,13,2
16,dspy_gemini_gpt4o-mini,per_class,dependence,+D,0.55,0.33,1.0,0.50,5,5,10,7,0
16,dspy_gemini_qwen72b,per_class,dependence,+D,0.73,0.43,0.6,0.50,5,3,4,13,2
16,dspy_agent_critic_gemini_gemma9b,per_class,dependence,+D,0.82,0.67,0.4,0.50,5,2,1,16,3
16,dspy_agent_critic_claude_gpt4o-mini,per_class,dependence,+D,0.68,0.38,0.6,0.46,5,3,5,12,2
16,dspy_agent_gemini_mistral7b,per_class,dependence,+D,0.68,0.38,0.6,0.46,5,3,5,12,2
16,dspy_agent_gemini_qwen72b,per_class,dependence,+D,0.68,0.38,0.6,0.46,5,3,5,12,2
16,dspy_agent_critic_claude_mistral-small-3.1,per_class,dependence,+D,0.73,0.40,0.4,0.40,5,2,3,14,3
16,dspy_agent_critic_gemini_llama70b,per_class,dependence,+D,0.73,0.40,0.4,0.40,5,2,3,14,3
16,dspy_agent_critic_claude_qwen72b,per_class,dependence,+D,0.73,0.40,0.4,0.40,5,2,3,14,3
16,dspy_claude_llama70b,per_class,dependence,+D,0.55,0.27,0.6,0.37,5,3,8,9,2

In [25]:
dependence_df[dependence_df['class'] == '-D'].sort_values(by='f1_score', ascending=False).head(20)

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
17,dspy_agent_gemini_gpt4o-mini,per_class,dependence,-D,0.86,0.89,0.94,0.91,17,16,2,3,1
17,dspy_gemini_llama8b,per_class,dependence,-D,0.82,0.93,0.82,0.87,17,14,1,4,3
17,dspy_agent_critic_claude_llama3b,per_class,dependence,-D,0.77,0.77,1.00,0.87,17,17,5,0,0
17,dspy_agent_gemini_gemma9b,per_class,dependence,-D,0.82,0.93,0.82,0.87,17,14,1,4,3
17,dspy_gemini_llama3b,per_class,dependence,-D,0.77,0.80,0.94,0.86,17,16,4,1,1
17,dspy_agent_critic_gemini_gpt4o-mini,per_class,dependence,-D,0.77,0.88,0.82,0.85,17,14,2,3,3
17,dspy_agent_critic_claude_gemma9b,per_class,dependence,-D,0.77,0.88,0.82,0.85,17,14,2,3,3
17,dspy_agent_gemini_mistral-small-3.1,per_class,dependence,-D,0.77,0.88,0.82,0.85,17,14,2,3,3
17,dspy_claude_llama3b,per_class,dependence,-D,0.73,0.76,0.94,0.84,17,16,5,0,1
17,dspy_agent_claude_gemma9b,per_class,dependence,-D,0.73,0.79,0.88,0.83,17,15,4,1,2
17,dspy_agent_critic_claude_qwen72b,per_class,dependence,-D,0.73,0.82,0.82,0.82,17,14,3,2,3
17,dspy_agent_critic_gemini_llama70b,per_class,dependence,-D,0.73,0.82,0.82,0.82,17,14,3,2,3
17,dspy_agent_gemini_llama8b,per_class,dependence,-D,0.73,0.87,0.76,0.81,17,13,2,3,4
17,dspy_agent_gemini_llama70b,per_class,dependence,-D,0.73,0.87,0.76,0.81,17,13,2,3,4
17,dspy_gemini_qwen72b,per_class,dependence,-D,0.73,0.87,0.76,0.81,17,13,2,3,4
17,dspy_agent_critic_gemini_mistral-small-3.1,per_class,dependence,-D,0.73,0.87,0.76,0.81,17,13,2,3,4
17,dspy_agent_claude_qwen72b,per_class,dependence,-D,0.68,0.75,0.88,0.81,17,15,5,0,2
17,dspy_agent_claude_gpt4o-mini,per_class,dependence,-D,0.68,0.75,0.88,0.81,17,15,5,0,2
17,dspy_agent_claude_mistral7b,per_class,dependence,-D,0.68,0.75,0.88,0.81,17,15,5,0,2
17,dspy_claude_qwen7b,per_class,dependence,-D,0.68,0.75,0.88,0.81,17,15,5,0,2

In [26]:
dependence_df['class'].unique()

array(['-D', '+D', 'all'], dtype=object)

---

## Find best DSPy models from each of dataset of:
* overall scores
* dependence scores
* identity scores
* own identity scores
* unity scores
* dependence scores

Results in 6 models

In [27]:
top_n = 1
top_models = list(
    set( pd.concat([
        overall_df.head(top_n),
        rigidity_df.head(top_n),
        identity_df.head(top_n),
        own_identity_df.head(top_n),
        unity_df.head(top_n),
        dependence_df.head(top_n)
    ]).agent_name
   )
)
top_models

['dspy_agent_gemini_gpt4o-mini',
 'dspy_gemini_mistral-small-3.1',
 'dspy_gemini_llama3b',
 'dspy_agent_critic_gemini_mistral-small-3.1',
 'dspy_agent_gemini_llama70b',
 'dspy_agent_critic_gemini_gpt4o-mini']

Look at overall scores for top models.  
Note: Gemini top models are much better. F1 scores are in range [0.77 - 0.69].

In [28]:
overall_df[overall_df.agent_name.isin(top_models)]

,agent_name,metric_type,property,class,accuracy,precision,recall,f1_score,support,tp,fp,tn,fn
0,dspy_gemini_mistral-small-3.1,overall,all,all,0.75,0.63,0.69,0.62,110,77,33,121,33
0,dspy_agent_gemini_llama70b,overall,all,all,0.76,0.63,0.66,0.60,110,78,32,122,32
0,dspy_agent_critic_gemini_gpt4o-mini,overall,all,all,0.73,0.62,0.65,0.58,110,74,36,118,36
0,dspy_agent_critic_gemini_mistral-small-3.1,overall,all,all,0.72,0.60,0.64,0.58,110,72,35,119,38
0,dspy_agent_gemini_gpt4o-mini,overall,all,all,0.69,0.63,0.61,0.55,110,69,41,113,41
0,dspy_gemini_llama3b,overall,all,all,0.71,0.61,0.50,0.50,110,72,38,116,38